name: Publish Fixed Staging

on:
  workflow_run:
    workflows:
      - Request PR for Fixed Staging
    types:
      - completed

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
